import g0 from './gallery/fulls/00.jpg';
import g1 from './gallery/fulls/01.jpg';
import g2 from './gallery/fulls/02.jpg';
import g3 from './gallery/fulls/03.jpg';
import g4 from './gallery/fulls/04.jpg';
import product1 from './products/333.jpg';
import product2 from './products/product2.jpg';
import product3 from './products/socialmedia.jpg';
export const arr =  [g0,g1,g2,g3,g4];
export const products =[product1,product2,product3];
